# AUTOUPDATE_COMMENT_bukkit_worldguard__123.jar

# Bukkit unfortunetly does not have an api, we need to the workarounds
# Expect this to break anytime bukkit changes how downloads are handled
- name: Get latest version
  ansible.builtin.uri:
    url: "https://dev.bukkit.org/projects/{{ file_project }}/files/latest"
    follow_redirects: false
    decompress: false
  register: version
  failed_when: version.location is undefined

- name: Update to latest version
  block:
    - name: Download latest version
      ansible.builtin.get_url:
        url: "{{ version.location }}"
        dest: "{{ new_file }}"
        headers:
          accept: application/octet-stream
        force: true
    
    - ansible.builtin.include_tasks: updates/actions/delete.yml
  
  when: build_id != file_build
  vars:
    url: "{{ version.location | urlsplit }}"
    path: "{{ url.path[1:] | split('/') }}"
    build_id: "{{ path.1 }}-{{ path.2 }}"
