# AUTOUPDATE_COMMENT_hangar_AuroraLS3:Plan-Player-Analytics_paper_123.jar
- name: Get latest version
  ansible.builtin.uri:
    url: "https://hangar.papermc.io/api/v1/projects/{{ file_project | replace(':', '/') }}/latestrelease"
    return_content: true
    headers:
      accept: text/plain
  register: releases

- name: Update to the latest version
  block:
    - name: Download latest release
      ansible.builtin.get_url:
        url: "https://hangar.papermc.io/api/v1/projects/{{ file_project | replace(':', '/') }}/versions/{{ releases.content }}/{{ file_version | upper }}/download"
        dest: "{{ new_file }}"
        headers:
          accept: application/octet-stream
        force: true
    
    - ansible.builtin.include_tasks: updates/actions/delete.yml
  
  when: build_id != file_build
  vars:
    build_id: "{{ releases.content | replace('_', '-') }}"
