# AUTOUPDATE_COMMENT_jenkins_ci.citizensnpcs.co_Citizens2_123.jar
- name: Get latest stable build
  ansible.builtin.uri:
    url: "https://{{ file_project | replace(':', '/') }}/lastStableBuild/api/json?tree=artifacts%5BrelativePath%5D,id"
    headers:
      accept: application/json
  register: stable_build

- name: Check that a build is avilable
  ansible.builtin.fail:
    msg: There is no stable jenkins build for {{ file_project | replace(':', '/') }}
  when: (stable_build.json is not defined) or stable_build.json == {}

- name: Update to the latest stable build
  block:
  - name: Check that the specified asset is attached
    ansible.builtin.fail:
      msg: "There is no file, which starts with '{{ file_version }}' and ends in .jar, in the latest (stable) jenkins build of '{{ file_project | replace(':', '/') }}'"
    when: (artifacts | length) == 0
  
  - name: Download latest stable build
    ansible.builtin.get_url:
      url: "https://{{ file_project | replace(':', '/') }}/lastStableBuild/artifact/{{ artifacts.0 }}"
      dest: "{{ new_file }}"
      headers:
        accept: application/octet-stream
      force: true
  
  - ansible.builtin.include_tasks: updates/actions/delete.yml
  
  when: (build_id | string) != file_build
  vars:
    artifacts: "{{ stable_build.json.artifacts | map(attribute='relativePath') | select('regex', regex_filter) }}"
    regex_filter: "^.*/{{ file_version | replace('#', '_') | regex_escape }}.*\\.jar$"
    build_id: "{{ stable_build.json.id }}"
