- block:
  - name: Check that targeted template exists
    ansible.builtin.fail:
      msg: "The template {{ sources.0 }} does not exist (or is not a directory)."
    when: not sources.0 is directory
    ignore_errors: true
  
  - name: Combine templates and overrides
    block:
      - name: Create tmp directory
        ansible.builtin.file:
          state: directory
          path: "{{ tmp_path }}"
        changed_when: false
      
      # We can't use ansible.posix.rsync because it does not support rsync on the same host
      - name: Copy template and overrides
        ansible.builtin.command: /usr/bin/rsync --delay-updates -F --compress --checksum --recursive --perms -S --exclude=.* --out-format='CHANGED >> %i %n%L' {{ item }}/ {{ tmp_path }}/
        loop: "{{ sources }}"
        changed_when: false
      
      - ansible.builtin.set_fact:
          tmp_dict: "{{ tmp_dict | combine( {dir_name: tmp_path} ) }}"
      
    when: sources.1 is directory
  
  - ansible.builtin.set_fact:
      tmp_dict: "{{ tmp_dict | combine( {dir_name: sources.0} ) }}"
    when: not sources.1 is directory

  delegate_to: localhost
  run_once: true
